namespace Domain_Layer.Enums
{
    public enum Categories
    {
        Antiques,
        Art,
        Baby,
        Books_and_Magazines,
        Business_and_Industrial,
        Cameras_and_Photo,
        Cell_Phones_and_Accessories,
        Clothing, Shoes_and_Accessories,
        Coins_and_Paper_Money,
        Collectibles,
        Computers_Tablets_and_Networking,
        Consumer_Electronics,
        Crafts,
        Dolls_and_Bears,
        Entertainment_Memorabilia,
        Everything_Else,
        Gift_Cards_and_Coupons,
        Health_and_Beauty,
        Home_and_Garden,
        Jewelry_and_Watches,
        Movies_and_TV,
        Music,
        Musical_Instruments_and_Gear,
        Pet_Supplies,
        Pottery_and_Glass,
        Real_Estate,
        Specialty_Services,
        Sporting_Goods,
        Sports_Mem, Cards_and_Fan_Shop,
        Stamps,
        Tickets_and_Experiences,
        Toys_and_Hobbies,
        Travel,
        Video_Games_and_Consoles,
    }
}
